spring.application.name=backend
whatsapp.token=${WHATSAPP_TOKEN}
whatsapp.phone-number-id=${WHATSAPP_PHONE_ID}
whatsapp.verify-token=${WHATSAPP_VERIFY_TOKEN}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

api.security.token.secret=${JWT_SECRET}